name: demucs

channels:
  - conda-forge
  - pytorch
  - fastai

dependencies:
  - python==3.7.8
  - ffmpeg==4.2
  - scipy==1.3.1
  - tqdm==4.36.1
  - voila==0.2.6
  - fastai==2.2.5
  - ipywidgets==7.5.1
  - pip
  - pip:
    - lameenc==1.2.2
    - musdb==0.3.1
    - museval==0.3.0
    - requests==2.22
    - treetable==0.2.3